#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

NAME=xlnetacc
PROG=/usr/bin/xlnetacc.sh

start_service() {
	config_load "$NAME"
	config_get_bool enabled "general" "enabled" 0
	config_get_bool down_acc "general" "down_acc" 0
	config_get_bool up_acc "general" "up_acc" 0
	config_get network "general" "network"
	config_get username "general" "account"
	config_get password "general" "password"

	[ "$enabled" -eq 1 ] || return 0
	[ "$down_acc" -eq 1 ] || [ "$up_acc" -eq 1 ] || return 0
	[ -n "$username" ] && [ -n "$password" ] && [ -n "$network" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" --start
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$NAME"
}
